version: '3.8'

# Development overrides for docker-compose.yml
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: devpassword123
    volumes:
      - mongodb_data_dev:/data/db
    ports:
      - "27017:27017"

  redis:
    command: redis-server --appendonly yes --requirepass devpassword123
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"

  redis-commander:
    environment:
      REDIS_HOSTS: local:redis:6379:0:devpassword123
    ports:
      - "8081:8081"

  mongo-express:
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpassword123
      ME_CONFIG_MONGODB_URL: mongodb://admin:devpassword123@mongodb:27017/

volumes:
  mongodb_data_dev:
    driver: local
  redis_data_dev:
    driver: local