version: '3.8'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - auth-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: [
      "start",
      "--http-port=8080",
      "--proxy-headers=forwarded",
      "--hostname-strict=false"
    ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: forwarded
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_IMPORT: /opt/keycloak/data/import/ssbhakthi-realm.json
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak/import:/opt/keycloak/data/import
    networks:
      - auth-network
    depends_on:
      - keycloak-db

volumes:
  keycloak-db-data:

networks:
  auth-network: