export class YexaaLocalConstant {
  Ritu = {
    name: ['వసంత', 'గ్రీష్మ', 'వర్షా', 'శరద్', 'హేమంత', 'శిశిర'],
    name_en_UK: ['Spring', 'Summer', 'Monsoon', 'Autumn', 'Pre-Winter', 'Winter'],
  };

  Masa = {
    name: [
      'వైశాఖ',
      'జ్యేష్ఠ',
      'ఆషాఢ',
      'శ్రావణ',
      'భాద్రపద',
      'ఆశ్వయుజ',
      'కార్తిక',
      'మార్గశిర',
      'పుష్య',
      'మాఘ',
      'ఫాల్గుణ',
      'చైత్ర',
    ],
    name_en_IN: [
      'vishakam',
      'jyesta',
      'ashada',
      'sravana',
      'badhrapada',
      'aswayuja',
      'karthika',
      'margasira',
      'pusya',
      'magha',
      'phalguna',
      'chaitra',
    ],
  };

  Raasi = {
    name: [
      'మేష',
      'వృషభ',
      'మిథున',
      'కర్కాటక',
      'సింహ',
      'కన్య',
      'తుల',
      'వృశ్చిక',
      'ధనుస్సు',
      'మకర',
      'కుంభ',
      'మీన',
    ],
    name_en_UK: [
      'Aries',
      'Taurus',
      'Gemini',
      'Cancer',
      'Leo',
      'Virgo',
      'Libra',
      'Scorpio',
      'Sagittarius',
      'Capricorn',
      'Aquarius',
      'Pisces',
    ],
  };

  Day = {
    name: ['ఆదివారం', 'సోమవారం', 'మంగళవారం', 'బుధవారం', 'గురువారం', 'శుక్రవారం', 'శనివారం'],
    name_en_UK: ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  };

  Nakshatra = {
    name: [
      'అశ్విని',
      'ద్విజ',
      'కృత్తిక',
      'రోహిణి',
      'మృగశిర',
      'ఆర్ద్ర',
      'పునర్వసు',
      'పుష్య',
      'ఆశ్లేష',
      'మఘ',
      'పూర్వఫల్గుణి',
      'ఉత్తరఫల్గుణి',
      'హస్త',
      'చిత్రా',
      'స్వాతి',
      'విశాఖ',
      'అనూరాధ',
      'జ్యేష్ఠ',
      'మూల',
      'పూర్వాషాఢ',
      'ఉత్తరాషాఢ',
      'శ్రవణ',
      'ధనిష్ఠ',
      'శతభిష',
      'పూర్వభాద్రపద',
      'ఉత్తరభాద్రపద',
      'రేవతి',
    ],
    name_en_IN: [
      'ashwini',
      'bharani',
      'krithika',
      'rohini',
      'mrigashirsha',
      'ardra',
      'punarvasu',
      'pushya',
      'ashlesha',
      'makha',
      'purva_phalguni',
      'uttara_phalguni',
      'hasta',
      'chitra',
      'swati',
      'vishaka',
      'anuradha',
      'jyeshta',
      'moola',
      'purva_ashadha',
      'uttara_ashadha',
      'shravana',
      'dhanishta',
      'shatabhisha',
      'purva_bhadrapada',
      'uttara_bhadrapada',
      'revati',
    ],
  };

  Paksha = {
    name_en_IN: ['shukla_paksha', 'krishna_paksha'],
    name_en_UK: ['Waxing Moon', 'Waning Moon'],
    name: ['శుక్ల', 'కృష్ణ'],
  };

  Tithi = {
    name: [
      'పాడ్యమి',
      'విదియ',
      'తదియ',
      'చవితి',
      'పంచమి',
      'షష్టి',
      'సప్తమి',
      'అష్టమి',
      'నవమి',
      'దశమి',
      'ఏకాదశి',
      'ద్వాదశి',
      'త్రయోదశి',
      'చతుర్దశి',
      'పౌర్ణమి',
      'పాడ్యమి',
      'విదియ',
      'తదియ',
      'చవితి',
      'పంచమి',
      'షష్టి',
      'సప్తమి',
      'అష్టమి',
      'నవమి',
      'దశమి',
      'ఏకాదశి',
      'ద్వాదశి',
      'త్రయోదశి',
      'చతుర్దశి',
      'అమావాస్య',
    ],
    name_en_IN: [
      'padyami',
      'vidhiya',
      'thadiya',
      'chaviti',
      'panchami',
      'shasti',
      'saptami',
      'ashtami',
      'navami',
      'dasami',
      'ekadasi',
      'dvadasi',
      'trayodasi',
      'chaturdasi',
      'pournami',
      'padyami',
      'vidhiya',
      'thadiya',
      'chaviti',
      'panchami',
      'shasti',
      'saptami',
      'ashtami',
      'navami',
      'dasami',
      'ekadasi',
      'dvadasi',
      'trayodasi',
      'chaturdasi',
      'amavasya',
    ],
  };

  Karna = {
    name_en_IN: [
      'bawa',
      'balava',
      'kaulava',
      'taitula',
      'garaja',
      'vanija',
      'vishti',
      'sakuna',
      'chatushpada',
      'nagava',
      'kimstughana',
    ],
    name: [
      'బవ',
      'బాలవ',
      'కౌలవ',
      'తైతిల',
      'గర',
      'వాణిజ్య',
      'విష్టి',
      'శకుని',
      'చతుష్పద',
      'నాగ',
      'కింస్తుఘ్న',
    ],
  };

  Yoga = {
    name_en_IN: [
      'vishkambha',
      'prithi',
      'ayushman',
      'saubhagya',
      'sobhana',
      'atiganda',
      'sukarman',
      'dhrithi',
      'soola',
      'ganda',
      'vridhi',
      'dhruva',
      'vyaghata',
      'harshana',
      'vajra',
      'siddhi',
      'vyatipata',
      'variyan',
      'parigha',
      'siva',
      'siddha',
      'sadhya',
      'subha',
      'sukla',
      'bramha',
      'indra',
      'vaidhruthi',
    ],
    name: [
      'విష్కంభ',
      'ప్రీతి',
      'ఆయుష్మాన్',
      'సౌభాగ్య',
      'శోభన',
      'అతిగండ',
      'సుకర్మ',
      'ధృతి',
      'శూల',
      'గండ',
      'వృద్ధి',
      'ధ్రువ',
      'వ్యాఘాత',
      'హర్షణ',
      'వజ్ర',
      'సిద్ధి',
      'వ్యతిపాత',
      'వరీయాన్',
      'పరిఘ',
      'శివ',
      'సిద్ధ',
      'సాధ్య',
      'శుభ',
      'శుక్ల',
      'బ్రహ్మ',
      'ఇంద్ర',
      'వైధృతి',
    ],
  };

  Trinity = {
    name_en_IN: ['Brahma', 'Vishnu', 'Shiva'],
    name: ['బ్రహ్మ', 'విష్ణు', 'శివ'],
  };

  Guna = {
    name_en_IN: ['Rajas', 'Tamas', 'Satva'],
    name_en_UK: [
      'passion, activity, movement',
      'ignorance, inertia, laziness',
      'goodness, calmness, harmonious',
    ],
    name: ['రాజస', 'తమస', 'సత్వ'],
  };

  Gana = {
    name_en_IN: ['Devata', 'Manushya', 'Rakshasa'],
    name_en_UK: ['God', 'Human', 'Demon'],
    name: ['దేవత', 'మనुष्य', 'రాక్షస'],
  };
}
